<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Central Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.02" os="Windows 7" host="RAPVHQLAB03"><DocLocation><![CDATA[C:\Users\thonav\Documents\Unified Functional Testing\CreateRentalAgreement]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[CreateRentalAgreement]]></DName>
<Res><![CDATA[CreateRentalAgreement]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="55" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[SIMS]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[12/28/2016 - 14:59:09]]></Time>
<TimeTick>1482958749</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\SIMS_Regression\Application_UAT\simspos.bat",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\SIMS_Regression\Application_UAT\simspos.bat",1]]></Details>
<Time><![CDATA[12/28/2016 - 14:59:09]]></Time>
<TimeTick>1482958749</TimeTick>
<NodeArgs eType="Replay" icon="58" nRep="11" status="Passed" >
<Disp><![CDATA[Run "C:\SIMS_Regression\Application_UAT\simspos.bat",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="58" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[12/28/2016 - 14:59:34]]></Time>
<TimeTick>1482958774</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[User ID.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/28/2016 - 14:59:34]]></Time>
<TimeTick>1482958774</TimeTick>
<NodeArgs eType="Replay" icon="60" nRep="15" >
<Disp><![CDATA[User ID.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[User ID.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/28/2016 - 14:59:59]]></Time>
<TimeTick>1482958799</TimeTick>
<NodeArgs eType="Replay" icon="60" nRep="18" >
<Disp><![CDATA[User ID.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[User ID.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:07]]></Time>
<TimeTick>1482958807</TimeTick>
<NodeArgs eType="Replay" icon="60" nRep="19" >
<Disp><![CDATA[User ID.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[User ID.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["3770001"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:07]]></Time>
<TimeTick>1482958807</TimeTick>
<NodeArgs eType="Replay" icon="60" nRep="21" >
<Disp><![CDATA[User ID.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Password1"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:08]]></Time>
<TimeTick>1482958808</TimeTick>
<NodeArgs eType="Replay" icon="60" nRep="23" >
<Disp><![CDATA[Password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:08]]></Time>
<TimeTick>1482958808</TimeTick>
<NodeArgs eType="Replay" icon="61" nRep="25" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="59" nRep="14" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[JFrame]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:26]]></Time>
<TimeTick>1482958826</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Drop Alert]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:26]]></Time>
<TimeTick>1482958826</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[No.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:26]]></Time>
<TimeTick>1482958826</TimeTick>
<NodeArgs eType="Replay" icon="61" nRep="30" >
<Disp><![CDATA[No.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="59" nRep="29" >
<Disp><![CDATA[Drop Alert]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[JFrame.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:31]]></Time>
<TimeTick>1482958831</TimeTick>
<NodeArgs eType="Replay" icon="62" nRep="31" >
<Disp><![CDATA[JFrame.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[JFrame.Maximize]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:31]]></Time>
<TimeTick>1482958831</TimeTick>
<NodeArgs eType="Replay" icon="62" nRep="33" >
<Disp><![CDATA[JFrame.Maximize]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[HomeScreen.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:32]]></Time>
<TimeTick>1482958832</TimeTick>
<NodeArgs eType="Replay" icon="61" nRep="35" >
<Disp><![CDATA[HomeScreen.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Quick Access]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaInternalFrame]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:32]]></Time>
<TimeTick>1482958832</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Agreement.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:32]]></Time>
<TimeTick>1482958832</TimeTick>
<NodeArgs eType="Replay" icon="64" nRep="38" >
<Disp><![CDATA[Agreement.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[New Agreement.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:33]]></Time>
<TimeTick>1482958833</TimeTick>
<NodeArgs eType="Replay" icon="61" nRep="40" >
<Disp><![CDATA[New Agreement.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="63" nRep="37" >
<Disp><![CDATA[Quick Access]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="62" nRep="28" >
<Disp><![CDATA[JFrame]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Agreement Type Selection]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:41]]></Time>
<TimeTick>1482958841</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[JComboBox.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:41]]></Time>
<TimeTick>1482958841</TimeTick>
<NodeArgs eType="Replay" icon="65" nRep="42" >
<Disp><![CDATA[JComboBox.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[JComboBox.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Rental"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:41]]></Time>
<TimeTick>1482958841</TimeTick>
<NodeArgs eType="Replay" icon="65" nRep="44" >
<Disp><![CDATA[JComboBox.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Continue.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:41]]></Time>
<TimeTick>1482958841</TimeTick>
<NodeArgs eType="Replay" icon="61" nRep="46" >
<Disp><![CDATA[Continue.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="59" nRep="41" >
<Disp><![CDATA[Agreement Type Selection]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[JFrame]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:42]]></Time>
<TimeTick>1482958842</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Customer Search]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaInternalFrame]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:42]]></Time>
<TimeTick>1482958842</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[First Name.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Sasha"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:42]]></Time>
<TimeTick>1482958842</TimeTick>
<NodeArgs eType="Replay" icon="60" nRep="50" >
<Disp><![CDATA[First Name.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Last Name.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Smith"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:42]]></Time>
<TimeTick>1482958842</TimeTick>
<NodeArgs eType="Replay" icon="60" nRep="52" >
<Disp><![CDATA[Last Name.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:43]]></Time>
<TimeTick>1482958843</TimeTick>
<NodeArgs eType="Replay" icon="61" nRep="54" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[CustomerSearchDetails.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 6]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:45]]></Time>
<TimeTick>1482958845</TimeTick>
<NodeArgs eType="Replay" icon="66" nRep="56" >
<Disp><![CDATA[CustomerSearchDetails.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[CustomerSearchDetails.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 7]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:45]]></Time>
<TimeTick>1482958845</TimeTick>
<NodeArgs eType="Replay" icon="66" nRep="58" >
<Disp><![CDATA[CustomerSearchDetails.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[CustomerSearchDetails.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 8]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:45]]></Time>
<TimeTick>1482958845</TimeTick>
<NodeArgs eType="Replay" icon="66" nRep="60" >
<Disp><![CDATA[CustomerSearchDetails.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[CustomerSearchDetails.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 9]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:45]]></Time>
<TimeTick>1482958845</TimeTick>
<NodeArgs eType="Replay" icon="66" nRep="62" >
<Disp><![CDATA[CustomerSearchDetails.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[CustomerSearchDetails.SelectRow]]></Obj>
<Details plainTxt="False" ><![CDATA[0]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:45]]></Time>
<TimeTick>1482958845</TimeTick>
<NodeArgs eType="Replay" icon="66" nRep="64" >
<Disp><![CDATA[CustomerSearchDetails.SelectRow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="63" nRep="49" >
<Disp><![CDATA[Customer Search]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="62" nRep="48" >
<Disp><![CDATA[JFrame]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Delivery Address Selection]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:48]]></Time>
<TimeTick>1482958848</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[JTable.SelectRow]]></Obj>
<Details plainTxt="False" ><![CDATA[0]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:48]]></Time>
<TimeTick>1482958848</TimeTick>
<NodeArgs eType="Replay" icon="66" nRep="67" >
<Disp><![CDATA[JTable.SelectRow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="59" nRep="66" >
<Disp><![CDATA[Delivery Address Selection]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Corenter]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:49]]></Time>
<TimeTick>1482958849</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[No.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:49]]></Time>
<TimeTick>1482958849</TimeTick>
<NodeArgs eType="Replay" icon="61" nRep="70" >
<Disp><![CDATA[No.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="59" nRep="69" >
<Disp><![CDATA[Corenter]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[JFrame]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:49]]></Time>
<TimeTick>1482958849</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Agreement Item Search]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaInternalFrame]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:49]]></Time>
<TimeTick>1482958849</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Condition.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["New"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:49]]></Time>
<TimeTick>1482958849</TimeTick>
<NodeArgs eType="Replay" icon="65" nRep="74" >
<Disp><![CDATA[Condition.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:50]]></Time>
<TimeTick>1482958850</TimeTick>
<NodeArgs eType="Replay" icon="61" nRep="76" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Items.ClickCell]]></Obj>
<Details plainTxt="False" ><![CDATA[2, 0, "LEFT", "NONE"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:53]]></Time>
<TimeTick>1482958853</TimeTick>
<NodeArgs eType="Replay" icon="66" nRep="78" >
<Disp><![CDATA[Items.ClickCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[AgreementItem.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[0, "Item #"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:53]]></Time>
<TimeTick>1482958853</TimeTick>
<NodeArgs eType="Replay" icon="66" nRep="80" >
<Disp><![CDATA[AgreementItem.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[AgreementItem.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[0, "Item Desc"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:53]]></Time>
<TimeTick>1482958853</TimeTick>
<NodeArgs eType="Replay" icon="66" nRep="82" >
<Disp><![CDATA[AgreementItem.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[AgreementItem.ClickCell]]></Obj>
<Details plainTxt="False" ><![CDATA[0, "Item #", "LEFT", "NONE"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:53]]></Time>
<TimeTick>1482958853</TimeTick>
<NodeArgs eType="Replay" icon="66" nRep="84" >
<Disp><![CDATA[AgreementItem.ClickCell]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="63" nRep="73" >
<Disp><![CDATA[Agreement Item Search]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Inventory Information]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaInternalFrame]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:55]]></Time>
<TimeTick>1482958855</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Cancel.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:55]]></Time>
<TimeTick>1482958855</TimeTick>
<NodeArgs eType="Replay" icon="61" nRep="87" >
<Disp><![CDATA[Cancel.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="63" nRep="86" >
<Disp><![CDATA[Inventory Information]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Agreement Item Search]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaInternalFrame]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:55]]></Time>
<TimeTick>1482958855</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Continue.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[12/28/2016 - 15:00:55]]></Time>
<TimeTick>1482958855</TimeTick>
<NodeArgs eType="Replay" icon="61" nRep="90" >
<Disp><![CDATA[Continue.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA["Agreement Item Search"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[12/28/2016 - 15:01:19]]></Time>
<TimeTick>1482958879</TimeTick>
<NodeArgs eType="Replay" icon="63" nRep="91" status="Warning" >
<Disp><![CDATA["Agreement Item Search"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA["Agreement Item Search"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>to_class=JavaInternalFrame<br>title=Agreement Item Search.*<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
to_description=JavaInternalFrame<br>]]></Details>
<Time><![CDATA[12/28/2016 - 15:01:19]]></Time>
<TimeTick>1482958879</TimeTick>
<NodeArgs eType="Replay" icon="67" nRep="92" >
<Disp><![CDATA["Agreement Item Search"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Corenter.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Item Selection"]]></Details>
<Time><![CDATA[12/28/2016 - 15:01:19]]></Time>
<TimeTick>1482958879</TimeTick>
<NodeArgs eType="Replay" icon="68" nRep="94" >
<Disp><![CDATA[Corenter.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA["Agreement Item Search"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[12/28/2016 - 15:01:41]]></Time>
<TimeTick>1482958901</TimeTick>
<NodeArgs eType="Replay" icon="63" nRep="95" status="Warning" >
<Disp><![CDATA["Agreement Item Search"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA["Agreement Item Search"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>to_class=JavaInternalFrame<br>title=Agreement Item Search.*<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
to_description=JavaInternalFrame<br>]]></Details>
<Time><![CDATA[12/28/2016 - 15:01:41]]></Time>
<TimeTick>1482958901</TimeTick>
<NodeArgs eType="Replay" icon="67" nRep="96" >
<Disp><![CDATA["Agreement Item Search"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Delivery Method.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[12/28/2016 - 15:01:41]]></Time>
<TimeTick>1482958901</TimeTick>
<NodeArgs eType="Replay" icon="61" nRep="98" >
<Disp><![CDATA[Delivery Method.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="63" nRep="89" status="Warning" >
<Disp><![CDATA[Agreement Item Search]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="62" nRep="72" status="Warning" >
<Disp><![CDATA[JFrame]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Delivery Method for Customer]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[12/28/2016 - 15:01:41]]></Time>
<TimeTick>1482958901</TimeTick>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Delivery.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[12/28/2016 - 15:01:41]]></Time>
<TimeTick>1482958901</TimeTick>
<NodeArgs eType="Replay" icon="69" nRep="101" >
<Disp><![CDATA[Delivery.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Date:.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["12/29/2016"]]></Details>
<Time><![CDATA[12/28/2016 - 15:01:41]]></Time>
<TimeTick>1482958901</TimeTick>
<NodeArgs eType="Replay" icon="60" nRep="103" >
<Disp><![CDATA[Date:.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Time:.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#1"]]></Details>
<Time><![CDATA[12/28/2016 - 15:01:41]]></Time>
<TimeTick>1482958901</TimeTick>
<NodeArgs eType="Replay" icon="65" nRep="105" >
<Disp><![CDATA[Time:.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Save.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[12/28/2016 - 15:01:41]]></Time>
<TimeTick>1482958901</TimeTick>
<NodeArgs eType="Replay" icon="61" nRep="107" >
<Disp><![CDATA[Save.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="59" nRep="100" >
<Disp><![CDATA[Delivery Method for Customer]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[JFrame]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[12/28/2016 - 15:02:03]]></Time>
<TimeTick>1482958923</TimeTick>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Agreement Item Search]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaInternalFrame]]></Details>
<Time><![CDATA[12/28/2016 - 15:02:03]]></Time>
<TimeTick>1482958923</TimeTick>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA["Agreement Item Search"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[12/28/2016 - 15:02:03]]></Time>
<TimeTick>1482958923</TimeTick>
<NodeArgs eType="Replay" icon="63" nRep="110" status="Warning" >
<Disp><![CDATA["Agreement Item Search"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA["Agreement Item Search"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>to_class=JavaInternalFrame<br>title=Agreement Item Search.*<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
to_description=JavaInternalFrame<br>]]></Details>
<Time><![CDATA[12/28/2016 - 15:02:03]]></Time>
<TimeTick>1482958923</TimeTick>
<NodeArgs eType="Replay" icon="67" nRep="111" >
<Disp><![CDATA["Agreement Item Search"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[Corenter.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Agreement Detail"]]></Details>
<Time><![CDATA[12/28/2016 - 15:02:03]]></Time>
<TimeTick>1482958923</TimeTick>
<NodeArgs eType="Replay" icon="68" nRep="113" >
<Disp><![CDATA[Corenter.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA["Agreement Item Search"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[12/28/2016 - 15:02:24]]></Time>
<TimeTick>1482958944</TimeTick>
<NodeArgs eType="Replay" icon="63" nRep="114" status="Warning" >
<Disp><![CDATA["Agreement Item Search"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA["Agreement Item Search"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>to_class=JavaInternalFrame<br>title=Agreement Item Search.*<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
to_description=JavaInternalFrame<br>]]></Details>
<Time><![CDATA[12/28/2016 - 15:02:24]]></Time>
<TimeTick>1482958944</TimeTick>
<NodeArgs eType="Replay" icon="67" nRep="115" >
<Disp><![CDATA["Agreement Item Search"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[Schedule.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Weekly"]]></Details>
<Time><![CDATA[12/28/2016 - 15:02:24]]></Time>
<TimeTick>1482958944</TimeTick>